// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkCourtAvailability = `-- name: CheckCourtAvailability :many
SELECT id, court_id, penyewa_id, booking_date, start_time, end_time, duration_hours, total_price, status, created_at FROM bookings
WHERE court_id = ?
AND booking_date = ?
AND status NOT IN ('cancelled')
AND (
    (start_time < ? AND end_time > ?) OR
    (start_time < ? AND end_time > ?) OR
    (start_time >= ? AND end_time <= ?)
)
`

type CheckCourtAvailabilityParams struct {
	CourtID     int64     `json:"court_id"`
	BookingDate time.Time `json:"booking_date"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	StartTime_2 time.Time `json:"start_time_2"`
	EndTime_2   time.Time `json:"end_time_2"`
	StartTime_3 time.Time `json:"start_time_3"`
	EndTime_3   time.Time `json:"end_time_3"`
}

func (q *Queries) CheckCourtAvailability(ctx context.Context, arg CheckCourtAvailabilityParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, checkCourtAvailability,
		arg.CourtID,
		arg.BookingDate,
		arg.StartTime,
		arg.EndTime,
		arg.StartTime_2,
		arg.EndTime_2,
		arg.StartTime_3,
		arg.EndTime_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.PenyewaID,
			&i.BookingDate,
			&i.StartTime,
			&i.EndTime,
			&i.DurationHours,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBooking = `-- name: CreateBooking :execresult
INSERT INTO bookings (court_id, penyewa_id, booking_date, start_time, end_time, duration_hours, total_price, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBookingParams struct {
	CourtID       int64          `json:"court_id"`
	PenyewaID     int64          `json:"penyewa_id"`
	BookingDate   time.Time      `json:"booking_date"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	DurationHours int32          `json:"duration_hours"`
	TotalPrice    float64        `json:"total_price"`
	Status        BookingsStatus `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBooking,
		arg.CourtID,
		arg.PenyewaID,
		arg.BookingDate,
		arg.StartTime,
		arg.EndTime,
		arg.DurationHours,
		arg.TotalPrice,
		arg.Status,
	)
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = ?
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, court_id, penyewa_id, booking_date, start_time, end_time, duration_hours, total_price, status, created_at FROM bookings WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.PenyewaID,
		&i.BookingDate,
		&i.StartTime,
		&i.EndTime,
		&i.DurationHours,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingsByCourt = `-- name: ListBookingsByCourt :many
SELECT id, court_id, penyewa_id, booking_date, start_time, end_time, duration_hours, total_price, status, created_at FROM bookings WHERE court_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByCourt(ctx context.Context, courtID int64) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByCourt, courtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.PenyewaID,
			&i.BookingDate,
			&i.StartTime,
			&i.EndTime,
			&i.DurationHours,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByOwner = `-- name: ListBookingsByOwner :many
SELECT b.id, b.court_id, b.penyewa_id, b.booking_date, b.start_time, b.end_time, b.duration_hours, b.total_price, b.status, b.created_at FROM bookings b
JOIN courts c ON b.court_id = c.id
WHERE c.owner_id = ?
ORDER BY b.created_at DESC
`

func (q *Queries) ListBookingsByOwner(ctx context.Context, ownerID int64) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.PenyewaID,
			&i.BookingDate,
			&i.StartTime,
			&i.EndTime,
			&i.DurationHours,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByPenyewa = `-- name: ListBookingsByPenyewa :many
SELECT id, court_id, penyewa_id, booking_date, start_time, end_time, duration_hours, total_price, status, created_at FROM bookings WHERE penyewa_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByPenyewa(ctx context.Context, penyewaID int64) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByPenyewa, penyewaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.PenyewaID,
			&i.BookingDate,
			&i.StartTime,
			&i.EndTime,
			&i.DurationHours,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings SET status = ? WHERE id = ?
`

type UpdateBookingStatusParams struct {
	Status BookingsStatus `json:"status"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingStatus, arg.Status, arg.ID)
	return err
}
