// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courts.sql

package db

import (
	"context"
	"database/sql"
)

const createCourt = `-- name: CreateCourt :execresult
INSERT INTO courts (owner_id, name, description, address, city, price_per_hour, status, avg_rating, total_reviews)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCourtParams struct {
	OwnerID      int64          `json:"owner_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Address      sql.NullString `json:"address"`
	City         sql.NullString `json:"city"`
	PricePerHour float64        `json:"price_per_hour"`
	Status       CourtsStatus   `json:"status"`
	AvgRating    float64        `json:"avg_rating"`
	TotalReviews int32          `json:"total_reviews"`
}

func (q *Queries) CreateCourt(ctx context.Context, arg CreateCourtParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourt,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.City,
		arg.PricePerHour,
		arg.Status,
		arg.AvgRating,
		arg.TotalReviews,
	)
}

const deleteCourt = `-- name: DeleteCourt :exec
DELETE FROM courts WHERE id = ?
`

func (q *Queries) DeleteCourt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCourt, id)
	return err
}

const getCourtByID = `-- name: GetCourtByID :one
SELECT id, owner_id, name, description, address, city, price_per_hour, status, avg_rating, total_reviews, created_at FROM courts WHERE id = ? LIMIT 1
`

func (q *Queries) GetCourtByID(ctx context.Context, id int64) (Court, error) {
	row := q.db.QueryRowContext(ctx, getCourtByID, id)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.City,
		&i.PricePerHour,
		&i.Status,
		&i.AvgRating,
		&i.TotalReviews,
		&i.CreatedAt,
	)
	return i, err
}

const listCourts = `-- name: ListCourts :many
SELECT id, owner_id, name, description, address, city, price_per_hour, status, avg_rating, total_reviews, created_at FROM courts WHERE status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListCourts(ctx context.Context) ([]Court, error) {
	rows, err := q.db.QueryContext(ctx, listCourts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Court
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.City,
			&i.PricePerHour,
			&i.Status,
			&i.AvgRating,
			&i.TotalReviews,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourtsByCity = `-- name: ListCourtsByCity :many
SELECT id, owner_id, name, description, address, city, price_per_hour, status, avg_rating, total_reviews, created_at FROM courts WHERE city = ? AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListCourtsByCity(ctx context.Context, city sql.NullString) ([]Court, error) {
	rows, err := q.db.QueryContext(ctx, listCourtsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Court
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.City,
			&i.PricePerHour,
			&i.Status,
			&i.AvgRating,
			&i.TotalReviews,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourtsByOwner = `-- name: ListCourtsByOwner :many
SELECT id, owner_id, name, description, address, city, price_per_hour, status, avg_rating, total_reviews, created_at FROM courts WHERE owner_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListCourtsByOwner(ctx context.Context, ownerID int64) ([]Court, error) {
	rows, err := q.db.QueryContext(ctx, listCourtsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Court
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.City,
			&i.PricePerHour,
			&i.Status,
			&i.AvgRating,
			&i.TotalReviews,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourt = `-- name: UpdateCourt :exec
UPDATE courts
SET name = ?, description = ?, address = ?, city = ?, price_per_hour = ?, status = ?
WHERE id = ?
`

type UpdateCourtParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Address      sql.NullString `json:"address"`
	City         sql.NullString `json:"city"`
	PricePerHour float64        `json:"price_per_hour"`
	Status       CourtsStatus   `json:"status"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateCourt(ctx context.Context, arg UpdateCourtParams) error {
	_, err := q.db.ExecContext(ctx, updateCourt,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.City,
		arg.PricePerHour,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateCourtRating = `-- name: UpdateCourtRating :exec
UPDATE courts
SET avg_rating = ?, total_reviews = ?
WHERE id = ?
`

type UpdateCourtRatingParams struct {
	AvgRating    float64 `json:"avg_rating"`
	TotalReviews int32   `json:"total_reviews"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateCourtRating(ctx context.Context, arg UpdateCourtRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateCourtRating, arg.AvgRating, arg.TotalReviews, arg.ID)
	return err
}
