// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: court_reviews.sql

package db

import (
	"context"
	"database/sql"
)

const createCourtReview = `-- name: CreateCourtReview :execresult
INSERT INTO court_reviews (booking_id, court_id, penyewa_id, rating, comment)
VALUES (?, ?, ?, ?, ?)
`

type CreateCourtReviewParams struct {
	BookingID int64          `json:"booking_id"`
	CourtID   int64          `json:"court_id"`
	PenyewaID int64          `json:"penyewa_id"`
	Rating    int8           `json:"rating"`
	Comment   sql.NullString `json:"comment"`
}

func (q *Queries) CreateCourtReview(ctx context.Context, arg CreateCourtReviewParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourtReview,
		arg.BookingID,
		arg.CourtID,
		arg.PenyewaID,
		arg.Rating,
		arg.Comment,
	)
}

const getReviewByBookingID = `-- name: GetReviewByBookingID :one
SELECT id, booking_id, court_id, penyewa_id, rating, comment, created_at FROM court_reviews WHERE booking_id = ? LIMIT 1
`

func (q *Queries) GetReviewByBookingID(ctx context.Context, bookingID int64) (CourtReview, error) {
	row := q.db.QueryRowContext(ctx, getReviewByBookingID, bookingID)
	var i CourtReview
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CourtID,
		&i.PenyewaID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, booking_id, court_id, penyewa_id, rating, comment, created_at FROM court_reviews WHERE id = ? LIMIT 1
`

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (CourtReview, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i CourtReview
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CourtID,
		&i.PenyewaID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewsByCourt = `-- name: ListReviewsByCourt :many
SELECT id, booking_id, court_id, penyewa_id, rating, comment, created_at FROM court_reviews WHERE court_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListReviewsByCourt(ctx context.Context, courtID int64) ([]CourtReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByCourt, courtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourtReview
	for rows.Next() {
		var i CourtReview
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.CourtID,
			&i.PenyewaID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByPenyewa = `-- name: ListReviewsByPenyewa :many
SELECT id, booking_id, court_id, penyewa_id, rating, comment, created_at FROM court_reviews WHERE penyewa_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListReviewsByPenyewa(ctx context.Context, penyewaID int64) ([]CourtReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByPenyewa, penyewaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourtReview
	for rows.Next() {
		var i CourtReview
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.CourtID,
			&i.PenyewaID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
