// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: court_images.sql

package db

import (
	"context"
	"database/sql"
)

const createCourtImage = `-- name: CreateCourtImage :execresult
INSERT INTO court_images (court_id, image_url, is_primary)
VALUES (?, ?, ?)
`

type CreateCourtImageParams struct {
	CourtID   int64  `json:"court_id"`
	ImageUrl  string `json:"image_url"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) CreateCourtImage(ctx context.Context, arg CreateCourtImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourtImage, arg.CourtID, arg.ImageUrl, arg.IsPrimary)
}

const deleteCourtImage = `-- name: DeleteCourtImage :exec
DELETE FROM court_images WHERE id = ?
`

func (q *Queries) DeleteCourtImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCourtImage, id)
	return err
}

const getCourtImages = `-- name: GetCourtImages :many
SELECT id, court_id, image_url, is_primary, created_at FROM court_images WHERE court_id = ? ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) GetCourtImages(ctx context.Context, courtID int64) ([]CourtImage, error) {
	rows, err := q.db.QueryContext(ctx, getCourtImages, courtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourtImage
	for rows.Next() {
		var i CourtImage
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.ImageUrl,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryImage = `-- name: SetPrimaryImage :exec
UPDATE court_images
SET is_primary = (id = ?)
WHERE court_id = ?
`

type SetPrimaryImageParams struct {
	ID      int64 `json:"id"`
	CourtID int64 `json:"court_id"`
}

func (q *Queries) SetPrimaryImage(ctx context.Context, arg SetPrimaryImageParams) error {
	_, err := q.db.ExecContext(ctx, setPrimaryImage, arg.ID, arg.CourtID)
	return err
}
