// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type BookingsStatus string

const (
	BookingsStatusPendingPayment BookingsStatus = "pending_payment"
	BookingsStatusPaid           BookingsStatus = "paid"
	BookingsStatusActive         BookingsStatus = "active"
	BookingsStatusCompleted      BookingsStatus = "completed"
	BookingsStatusCancelled      BookingsStatus = "cancelled"
)

func (e *BookingsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingsStatus(s)
	case string:
		*e = BookingsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingsStatus: %T", src)
	}
	return nil
}

type NullBookingsStatus struct {
	BookingsStatus BookingsStatus `json:"bookings_status"`
	Valid          bool           `json:"valid"` // Valid is true if BookingsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingsStatus), nil
}

type CourtsStatus string

const (
	CourtsStatusActive      CourtsStatus = "active"
	CourtsStatusInactive    CourtsStatus = "inactive"
	CourtsStatusMaintenance CourtsStatus = "maintenance"
)

func (e *CourtsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourtsStatus(s)
	case string:
		*e = CourtsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourtsStatus: %T", src)
	}
	return nil
}

type NullCourtsStatus struct {
	CourtsStatus CourtsStatus `json:"courts_status"`
	Valid        bool         `json:"valid"` // Valid is true if CourtsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourtsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourtsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourtsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourtsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourtsStatus), nil
}

type NotificationsType string

const (
	NotificationsTypeBookingConfirmed NotificationsType = "booking_confirmed"
	NotificationsTypePaymentSuccess   NotificationsType = "payment_success"
	NotificationsTypePaymentFailed    NotificationsType = "payment_failed"
)

func (e *NotificationsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationsType(s)
	case string:
		*e = NotificationsType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationsType: %T", src)
	}
	return nil
}

type NullNotificationsType struct {
	NotificationsType NotificationsType `json:"notifications_type"`
	Valid             bool              `json:"valid"` // Valid is true if NotificationsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationsType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationsType), nil
}

type PaymentsStatus string

const (
	PaymentsStatusPending    PaymentsStatus = "pending"
	PaymentsStatusSettlement PaymentsStatus = "settlement"
	PaymentsStatusExpire     PaymentsStatus = "expire"
	PaymentsStatusFailure    PaymentsStatus = "failure"
)

func (e *PaymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsStatus(s)
	case string:
		*e = PaymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsStatus: %T", src)
	}
	return nil
}

type NullPaymentsStatus struct {
	PaymentsStatus PaymentsStatus `json:"payments_status"`
	Valid          bool           `json:"valid"` // Valid is true if PaymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsStatus), nil
}

type UsersRole string

const (
	UsersRoleSuperuser UsersRole = "superuser"
	UsersRoleOwner     UsersRole = "owner"
	UsersRolePenyewa   UsersRole = "penyewa"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type UsersStatus string

const (
	UsersStatusActive   UsersStatus = "active"
	UsersStatusInactive UsersStatus = "inactive"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type Booking struct {
	ID            int64          `json:"id"`
	CourtID       int64          `json:"court_id"`
	PenyewaID     int64          `json:"penyewa_id"`
	BookingDate   time.Time      `json:"booking_date"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	DurationHours int32          `json:"duration_hours"`
	TotalPrice    float64        `json:"total_price"`
	Status        BookingsStatus `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Court struct {
	ID           int64          `json:"id"`
	OwnerID      int64          `json:"owner_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Address      sql.NullString `json:"address"`
	City         sql.NullString `json:"city"`
	PricePerHour float64        `json:"price_per_hour"`
	Status       CourtsStatus   `json:"status"`
	AvgRating    float64        `json:"avg_rating"`
	TotalReviews int32          `json:"total_reviews"`
	CreatedAt    time.Time      `json:"created_at"`
}

type CourtImage struct {
	ID        int64     `json:"id"`
	CourtID   int64     `json:"court_id"`
	ImageUrl  string    `json:"image_url"`
	IsPrimary bool      `json:"is_primary"`
	CreatedAt time.Time `json:"created_at"`
}

type CourtReview struct {
	ID        int64          `json:"id"`
	BookingID int64          `json:"booking_id"`
	CourtID   int64          `json:"court_id"`
	PenyewaID int64          `json:"penyewa_id"`
	Rating    int8           `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
}

type Notification struct {
	ID        int64             `json:"id"`
	UserID    int64             `json:"user_id"`
	Type      NotificationsType `json:"type"`
	Title     string            `json:"title"`
	Body      string            `json:"body"`
	RefID     sql.NullInt64     `json:"ref_id"`
	IsRead    bool              `json:"is_read"`
	CreatedAt time.Time         `json:"created_at"`
}

type Payment struct {
	ID              int64          `json:"id"`
	BookingID       int64          `json:"booking_id"`
	MidtransOrderID string         `json:"midtrans_order_id"`
	MidtransTxID    sql.NullString `json:"midtrans_tx_id"`
	Amount          float64        `json:"amount"`
	FeeAmount       float64        `json:"fee_amount"`
	NetToOwner      float64        `json:"net_to_owner"`
	PaymentMethod   sql.NullString `json:"payment_method"`
	Status          PaymentsStatus `json:"status"`
	PaidAt          sql.NullTime   `json:"paid_at"`
	CreatedAt       time.Time      `json:"created_at"`
}

type PlatformSetting struct {
	ID         int64     `json:"id"`
	FeePercent float64   `json:"fee_percent"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Email      string         `json:"email"`
	Password   string         `json:"password"`
	Phone      sql.NullString `json:"phone"`
	Role       UsersRole      `json:"role"`
	IsVerified bool           `json:"is_verified"`
	Status     UsersStatus    `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
}
