// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO notifications (user_id, type, title, body, ref_id, is_read)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	UserID int64             `json:"user_id"`
	Type   NotificationsType `json:"type"`
	Title  string            `json:"title"`
	Body   string            `json:"body"`
	RefID  sql.NullInt64     `json:"ref_id"`
	IsRead bool              `json:"is_read"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.RefID,
		arg.IsRead,
	)
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, body, ref_id, is_read, created_at FROM notifications WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsByUser(ctx context.Context, userID int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RefID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications SET is_read = true WHERE user_id = ?
`

func (q *Queries) MarkAllAsRead(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, markAllAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications SET is_read = true WHERE id = ?
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, id)
	return err
}
