// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO payments (booking_id, midtrans_order_id, amount, fee_amount, net_to_owner, payment_method, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	BookingID       int64          `json:"booking_id"`
	MidtransOrderID string         `json:"midtrans_order_id"`
	Amount          float64        `json:"amount"`
	FeeAmount       float64        `json:"fee_amount"`
	NetToOwner      float64        `json:"net_to_owner"`
	PaymentMethod   sql.NullString `json:"payment_method"`
	Status          PaymentsStatus `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment,
		arg.BookingID,
		arg.MidtransOrderID,
		arg.Amount,
		arg.FeeAmount,
		arg.NetToOwner,
		arg.PaymentMethod,
		arg.Status,
	)
}

const getPaymentByBookingID = `-- name: GetPaymentByBookingID :one
SELECT id, booking_id, midtrans_order_id, midtrans_tx_id, amount, fee_amount, net_to_owner, payment_method, status, paid_at, created_at FROM payments WHERE booking_id = ? LIMIT 1
`

func (q *Queries) GetPaymentByBookingID(ctx context.Context, bookingID int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.MidtransOrderID,
		&i.MidtransTxID,
		&i.Amount,
		&i.FeeAmount,
		&i.NetToOwner,
		&i.PaymentMethod,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, midtrans_order_id, midtrans_tx_id, amount, fee_amount, net_to_owner, payment_method, status, paid_at, created_at FROM payments WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.MidtransOrderID,
		&i.MidtransTxID,
		&i.Amount,
		&i.FeeAmount,
		&i.NetToOwner,
		&i.PaymentMethod,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByMidtransOrderID = `-- name: GetPaymentByMidtransOrderID :one
SELECT id, booking_id, midtrans_order_id, midtrans_tx_id, amount, fee_amount, net_to_owner, payment_method, status, paid_at, created_at FROM payments WHERE midtrans_order_id = ? LIMIT 1
`

func (q *Queries) GetPaymentByMidtransOrderID(ctx context.Context, midtransOrderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByMidtransOrderID, midtransOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.MidtransOrderID,
		&i.MidtransTxID,
		&i.Amount,
		&i.FeeAmount,
		&i.NetToOwner,
		&i.PaymentMethod,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, booking_id, midtrans_order_id, midtrans_tx_id, amount, fee_amount, net_to_owner, payment_method, status, paid_at, created_at FROM payments ORDER BY created_at DESC
`

func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.MidtransOrderID,
			&i.MidtransTxID,
			&i.Amount,
			&i.FeeAmount,
			&i.NetToOwner,
			&i.PaymentMethod,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE payments
SET midtrans_tx_id = ?, payment_method = ?, status = ?, paid_at = ?
WHERE id = ?
`

type UpdatePaymentParams struct {
	MidtransTxID  sql.NullString `json:"midtrans_tx_id"`
	PaymentMethod sql.NullString `json:"payment_method"`
	Status        PaymentsStatus `json:"status"`
	PaidAt        sql.NullTime   `json:"paid_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, updatePayment,
		arg.MidtransTxID,
		arg.PaymentMethod,
		arg.Status,
		arg.PaidAt,
		arg.ID,
	)
	return err
}
