// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_settings.sql

package db

import (
	"context"
)

const getPlatformSettings = `-- name: GetPlatformSettings :one
SELECT id, fee_percent, updated_at FROM platform_settings ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetPlatformSettings(ctx context.Context) (PlatformSetting, error) {
	row := q.db.QueryRowContext(ctx, getPlatformSettings)
	var i PlatformSetting
	err := row.Scan(&i.ID, &i.FeePercent, &i.UpdatedAt)
	return i, err
}

const updatePlatformSettings = `-- name: UpdatePlatformSettings :exec
UPDATE platform_settings SET fee_percent = ? WHERE id = ?
`

type UpdatePlatformSettingsParams struct {
	FeePercent float64 `json:"fee_percent"`
	ID         int64   `json:"id"`
}

func (q *Queries) UpdatePlatformSettings(ctx context.Context, arg UpdatePlatformSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlatformSettings, arg.FeePercent, arg.ID)
	return err
}
