// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckCourtAvailability(ctx context.Context, arg CheckCourtAvailabilityParams) ([]Booking, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (sql.Result, error)
	CreateCourt(ctx context.Context, arg CreateCourtParams) (sql.Result, error)
	CreateCourtImage(ctx context.Context, arg CreateCourtImageParams) (sql.Result, error)
	CreateCourtReview(ctx context.Context, arg CreateCourtReviewParams) (sql.Result, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteAllUserTokens(ctx context.Context, userID int64) error
	DeleteBooking(ctx context.Context, id int64) error
	DeleteCourt(ctx context.Context, id int64) error
	DeleteCourtImage(ctx context.Context, id int64) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id int64) error
	GetBookingByID(ctx context.Context, id int64) (Booking, error)
	GetCourtByID(ctx context.Context, id int64) (Court, error)
	GetCourtImages(ctx context.Context, courtID int64) ([]CourtImage, error)
	GetPaymentByBookingID(ctx context.Context, bookingID int64) (Payment, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetPaymentByMidtransOrderID(ctx context.Context, midtransOrderID string) (Payment, error)
	GetPlatformSettings(ctx context.Context) (PlatformSetting, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetReviewByBookingID(ctx context.Context, bookingID int64) (CourtReview, error)
	GetReviewByID(ctx context.Context, id int64) (CourtReview, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListBookingsByCourt(ctx context.Context, courtID int64) ([]Booking, error)
	ListBookingsByOwner(ctx context.Context, ownerID int64) ([]Booking, error)
	ListBookingsByPenyewa(ctx context.Context, penyewaID int64) ([]Booking, error)
	ListCourts(ctx context.Context) ([]Court, error)
	ListCourtsByCity(ctx context.Context, city sql.NullString) ([]Court, error)
	ListCourtsByOwner(ctx context.Context, ownerID int64) ([]Court, error)
	ListNotificationsByUser(ctx context.Context, userID int64) ([]Notification, error)
	ListPayments(ctx context.Context) ([]Payment, error)
	ListReviewsByCourt(ctx context.Context, courtID int64) ([]CourtReview, error)
	ListReviewsByPenyewa(ctx context.Context, penyewaID int64) ([]CourtReview, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkAllAsRead(ctx context.Context, userID int64) error
	MarkNotificationAsRead(ctx context.Context, id int64) error
	SetPrimaryImage(ctx context.Context, arg SetPrimaryImageParams) error
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpdateCourt(ctx context.Context, arg UpdateCourtParams) error
	UpdateCourtRating(ctx context.Context, arg UpdateCourtRatingParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdatePlatformSettings(ctx context.Context, arg UpdatePlatformSettingsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
