// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verifications.sql

package db

import (
	"context"
	"time"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (user_id, token, expires_at)
VALUES (?, ?, ?)
`

type CreateEmailVerificationParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteEmailVerificationsByUser = `-- name: DeleteEmailVerificationsByUser :exec
DELETE FROM email_verifications WHERE user_id = ?
`

func (q *Queries) DeleteEmailVerificationsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerificationsByUser, userID)
	return err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT id, user_id, token, expires_at, used_at, created_at FROM email_verifications
WHERE token = ?
  AND used_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications
SET used_at = NOW()
WHERE token = ?
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markEmailVerificationUsed, token)
	return err
}
