// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteAllRefreshTokensByUser(ctx context.Context, userID int64) error
	DeleteEmailVerificationsByUser(ctx context.Context, userID int64) error
	DeleteRefreshToken(ctx context.Context, token string) error
	GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	MarkEmailVerificationUsed(ctx context.Context, token string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
